sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#自行填写你的AliyunOSS
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name: