sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#自行填写你自己的AliOSS对象存储配置信息
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10