sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: https://oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5t8TXr8RpjbBwk6LSsv7
    access-key-secret: 39UmvSLRkoR3WTotE5SxnooBdo2Vsu
    bucket-name: sky-take-out-zyy1

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

    #这里需要配置你的wechatappid和secret
  wechat:
    appid:
    secret: